2022/07/01 17:50:18 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "i". in D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('i')
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/i
---
2022/07/01 17:51:20 [error] [exception.CException] CException: Alias "application.models.Product" is invalid. Make sure it points to an existing PHP file and the file is readable. in D:\xampp\htdocs\yii_fw\yii_app\framework\YiiBase.php:330
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\gii\generators\crud\CrudCode.php(59): YiiBase::import('application.mod...', true)
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\validators\CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#2 D:\xampp\htdocs\yii_fw\yii_app\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#3 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CModel.php(159): CValidator->validate(Object(CrudCode), Array)
#4 D:\xampp\htdocs\yii_fw\yii_app\framework\gii\CCodeGenerator.php(159): CModel->validate()
#5 D:\xampp\htdocs\yii_fw\yii_app\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#6 D:\xampp\htdocs\yii_fw\yii_app\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#7 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(282): CController->run('index')
#11 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#12 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/gii/crud/index
HTTP_REFERER=http://yii_fw.com/index.php/gii/crud/index
---
2022/07/01 17:52:01 [error] [exception.CException] CException: Alias "application.models.Product" is invalid. Make sure it points to an existing PHP file and the file is readable. in D:\xampp\htdocs\yii_fw\yii_app\framework\YiiBase.php:330
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\gii\generators\crud\CrudCode.php(59): YiiBase::import('application.mod...', true)
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\validators\CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#2 D:\xampp\htdocs\yii_fw\yii_app\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#3 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CModel.php(159): CValidator->validate(Object(CrudCode), Array)
#4 D:\xampp\htdocs\yii_fw\yii_app\framework\gii\CCodeGenerator.php(159): CModel->validate()
#5 D:\xampp\htdocs\yii_fw\yii_app\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#6 D:\xampp\htdocs\yii_fw\yii_app\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#7 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(282): CController->run('index')
#11 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#12 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/gii/crud/index
HTTP_REFERER=http://yii_fw.com/index.php/gii/crud/index
---
2022/07/01 17:52:47 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii_fw.event' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Event`.
in D:\xampp\htdocs\yii_fw\index.php (13)
2022/07/01 20:58:50 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "equirements/index.php". in D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('equirements/ind...')
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/equirements/index.php
---
2022/07/01 20:58:54 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "requirements/index.php". in D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('requirements/in...')
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/requirements/index.php
---
2022/07/01 20:59:04 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "requirements". in D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('requirements')
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/requirements/
---
2022/07/02 06:09:32 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii_fw.com/
---
2022/07/02 07:01:49 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "evnet". in D:\xampp\htdocs\yii_fw\protected\vendor\yiisoft\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\protected\vendor\yiisoft\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('evnet')
#1 D:\xampp\htdocs\yii_fw\protected\vendor\yiisoft\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/evnet
---
2022/07/02 18:44:23 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii_fw\yii_app\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\xampp\htdocs\yii_fw\yii_app\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii_fw\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii_fw.com/
---
